name: "🐛 Bug"
description: Something doesn't work the way we expected.
title: ""
labels: ["bug"]
body:
  - type: textarea
    id: did
    attributes:
      label: What I did
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What I expected
    validations:
      required: true
  - type: textarea
    id: happened
    attributes:
      label: What happened (paste any red error from the console)
    validations:
      required: true
